import 'package:gogo/ui/user_screens/map_screen/data/model/map_suggestion_model.dart';

class CustomLocationService {
  static final List<MapSuggestion> _customLocations = [
    MapSuggestion(
      id: "north_1",
      name: "السكاسكه",
      latitude: 31.1300,
      longitude: 33.8200,
      address: "قرية السكاسكه، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_2",
      name: "الخروبه",
      latitude: 31.18378,
      longitude: 33.97059,
      address: "الخروبة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_3",
      name: "قبر عمير",
      latitude: 31.1800,
      longitude: 33.9800,
      address: "قبر عمير، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_4",
      name: "الشيخ زويد",
      latitude: 31.0708983,
      longitude: 34.1857941,
      address: "مدينة الشيخ زويد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_5",
      name: "رفح الجديدة",
      latitude: 31.3000,
      longitude: 34.2500,
      address: "رفح الجديدة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_6",
      name: "معبر رفح البري",
      latitude: 31.2936,
      longitude: 34.2425,
      address: "معبر رفح البري، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_7",
      name: "البرس",
      latitude: 31.1200,
      longitude: 34.0500,
      address: "قرية البرس، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_8",
      name: "النخل",
      latitude: 29.9062971,
      longitude: 33.7427293,
      address: "مدينة النخل، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_9",
      name: "الحسنة",
      latitude: 30.5917,
      longitude: 33.8000,
      address: "مدينة الحسنة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_10",
      name: "القصيمه",
      latitude: 30.6000,
      longitude: 33.7000,
      address: "منطقة القصيمة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_11",
      name: "معبر العوجه",
      latitude: 31.2000,
      longitude: 34.2000,
      address: "معبر العوجة الحدودي، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_12",
      name: "العريش",
      latitude: 31.1310,
      longitude: 33.7980,
      address: "مدينة العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_13",
      name: "جامعة العريش",
      latitude: 31.1343,
      longitude: 33.7854,
      address: "جامعة العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_uni_arish_private",
      name: "جامعة العريش الخاصة",
      latitude: 31.136965323617,
      longitude: 33.8289294,
      address: "جامعة العريش الخاصة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_14",
      name: "بئر العبد",
      latitude: 31.2411,
      longitude: 33.9310,
      address: "مدينة بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_15",
      name: "رمانة",
      latitude: 31.0500,
      longitude: 33.7500,
      address: "رمانة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_16",
      name: "نجيلة",
      latitude: 31.0000,
      longitude: 33.7000,
      address: "نجيلة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_17",
      name: "الجورة",
      latitude: 31.0000,
      longitude: 34.0000,
      address: "الجورة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_18",
      name: "الميدان",
      latitude: 31.1500,
      longitude: 33.9000,
      address: "الميدان، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_19",
      name: "المساعيد",
      latitude: 31.1200,
      longitude: 33.8200,
      address: "المساعيد، العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_20",
      name: "زرزارة",
      latitude: 31.1400,
      longitude: 33.8100,
      address: "زرزارة، العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_21",
      name: "المطلة",
      latitude: 31.1450,
      longitude: 33.8400,
      address: "المطلة، العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_22",
      name: "أبو العراج",
      latitude: 31.1200,
      longitude: 34.2000,
      address: "أبو العراج، الشيخ زويد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_23",
      name: "أبو الفيتة",
      latitude: 31.1300,
      longitude: 34.2100,
      address: "أبو الفيتة، الشيخ زويد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_24",
      name: "أبو شنار",
      latitude: 31.1400,
      longitude: 34.2200,
      address: "أبو شنار، رفح، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_25",
      name: "أبي صقل",
      latitude: 31.1500,
      longitude: 34.2300,
      address: "أبي صقل، العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_26",
      name: "أقطية",
      latitude: 31.1600,
      longitude: 34.2400,
      address: "أقطية، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_27",
      name: "أم شيحان",
      latitude: 31.1700,
      longitude: 34.2500,
      address: "أم شيحان، الحسنة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_28",
      name: "أم عقبة",
      latitude: 31.1800,
      longitude: 34.2600,
      address: "أم عقبة، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_29",
      name: "أم قطف",
      latitude: 31.1900,
      longitude: 34.2700,
      address: "أم قطف، الحسنة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_30",
      name: "الأحرار",
      latitude: 31.2000,
      longitude: 34.2800,
      address: "الأحرار، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_31",
      name: "البرث",
      latitude: 31.2100,
      longitude: 34.2900,
      address: "البرث، رفح، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_32",
      name: "البروك",
      latitude: 31.2200,
      longitude: 34.3000,
      address: "البروك، نخل، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_33",
      name: "التلول",
      latitude: 31.2300,
      longitude: 34.3100,
      address: "التلول، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_34",
      name: "التمد",
      latitude: 31.2400,
      longitude: 34.3200,
      address: "التمد، نخل، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_35",
      name: "الجدي",
      latitude: 31.2500,
      longitude: 34.3300,
      address: "الجدي، الحسنة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_36",
      name: "الجفجافة",
      latitude: 31.2600,
      longitude: 34.3400,
      address: "الجفجافة، الحسنة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_37",
      name: "الجناين",
      latitude: 31.2700,
      longitude: 34.3500,
      address: "الجناين، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_38",
      name: "الجورة",
      latitude: 31.2800,
      longitude: 34.3600,
      address: "الجورة، الشيخ زويد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_39",
      name: "الحماد",
      latitude: 31.2900,
      longitude: 34.3700,
      address: "الحماد، رفح، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_40",
      name: "الحمام",
      latitude: 31.3000,
      longitude: 34.3800,
      address: "الحمام، العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_41",
      name: "الخربة",
      latitude: 31.3100,
      longitude: 34.3900,
      address: "الخربة، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_42",
      name: "الخروبة",
      latitude: 31.3200,
      longitude: 34.4000,
      address: "الخروبة، الشيخ زويد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_43",
      name: "الخفجة",
      latitude: 31.3300,
      longitude: 34.4100,
      address: "الخفجة، نخل، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_44",
      name: "الروضة",
      latitude: 31.3400,
      longitude: 34.4200,
      address: "الروضة، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_45",
      name: "الريسان",
      latitude: 31.3500,
      longitude: 34.4300,
      address: "الريسان، الحسنة، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_46",
      name: "الزهراء",
      latitude: 31.3600,
      longitude: 34.4400,
      address: "الزهراء، العريش، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_47",
      name: "الزوارعة",
      latitude: 31.3700,
      longitude: 34.4500,
      address: "الزوارعة، الشيخ زويد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_48",
      name: "السادات",
      latitude: 31.3800,
      longitude: 34.4600,
      address: "السادات، بئر العبد، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_49",
      name: "السلام",
      latitude: 31.3900,
      longitude: 34.4700,
      address: "السلام، نخل، شمال سيناء، مصر",
    ),
    MapSuggestion(
      id: "north_50",
      name: "السكادرة",
      latitude: 31.4000,
      longitude: 34.4800,
      address: "السكادرة، الشيخ زويد، شمال سيناء، مصر",
    ),
  ];

  static List<MapSuggestion> getCustomLocations() => _customLocations;

  static List<MapSuggestion> searchCustomLocations(String query) {
    final lower = query.toLowerCase();
    return _customLocations.where((loc) {
      return loc.name.toLowerCase().contains(lower) ||
          (loc.address?.toLowerCase().contains(lower) ?? false);
    }).toList();
  }
}
