// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfETP5-OvzNKQu7BomagxyE4AV1GJxHXw',
    appId: '1:311802383612:web:7bca517e65ed1eb1eb5b79',
    messagingSenderId: '311802383612',
    projectId: 'gogo-app-6ef48',
    authDomain: 'gogo-app-6ef48.firebaseapp.com',
    storageBucket: 'gogo-app-6ef48.firebasestorage.app',
    measurementId: 'G-WRC9VSTG09',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFBY26pIokzgXnpN5dMpPNu5Z_g-DfDdI',
    appId: '1:311802383612:android:a6c4220c5d6c440eeb5b79',
    messagingSenderId: '311802383612',
    projectId: 'gogo-app-6ef48',
    storageBucket: 'gogo-app-6ef48.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCenBp12tBNZZVT0ex3ZWEzB9qeQ3CEXIs',
    appId: '1:311802383612:ios:c0301e907f9353e5eb5b79',
    messagingSenderId: '311802383612',
    projectId: 'gogo-app-6ef48',
    storageBucket: 'gogo-app-6ef48.firebasestorage.app',
    iosBundleId: 'com.eyad.gogo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCenBp12tBNZZVT0ex3ZWEzB9qeQ3CEXIs',
    appId: '1:311802383612:ios:3842e5d0b50bdb43eb5b79',
    messagingSenderId: '311802383612',
    projectId: 'gogo-app-6ef48',
    storageBucket: 'gogo-app-6ef48.firebasestorage.app',
    iosBundleId: 'com.example.gogo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfETP5-OvzNKQu7BomagxyE4AV1GJxHXw',
    appId: '1:311802383612:web:ad2225b13df4008aeb5b79',
    messagingSenderId: '311802383612',
    projectId: 'gogo-app-6ef48',
    authDomain: 'gogo-app-6ef48.firebaseapp.com',
    storageBucket: 'gogo-app-6ef48.firebasestorage.app',
    measurementId: 'G-WDJLVTBZN0',
  );
}
